# python scripts/train.py --config_name="beta_tracking" --strategy="information" --seed=0 --logdir="beta_tracking"
# python scripts/train.py --config_name="beta_rotation" --strategy="information" --seed=0 --logdir="beta_rotation"
# python scripts/train.py --config_name="cartpole" --strategy="information" --seed=0 --logdir="cartpole"
# python scripts/train.py --config_name="pendulum" --strategy="information" --seed=0 --logdir="pendulum"
python scripts/train.py --config_name="barl_reacher" --strategy="information" --seed=0 --logdir="reacher"
